name: clean_architecture
description: Clean Architecture

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  http: ^0.13.5
  provider: ^6.0.4

dev_dependencies:
  alchemist: ^0.5.1
  bloc_test: ^9.1.0
  build_runner: null
  file: ^6.1.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  integration_test:
    sdk: flutter
  mockito: ^5.3.2
  mocktail: ^0.3.0
  platform: ^3.1.0

flutter:
  uses-material-design: true
